FROM node:14.17.5-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

ARG USE_AUTH=false
ARG SMICS_HOSTNAME=smics-core
ARG SMICS_PORT=9787
ARG AUTH_PROVIDER_URL=
ARG AUTH_REALM=
ARG AUTH_CLIENT_ID=
ARG AUTH_CLIENT_SECRET=
ENV USE_AUTH=$USE_AUTH
ENV SMICS_HOSTNAME=$SMICS_HOSTNAME
ENV SMICS_PORT=$SMICS_PORT
ENV AUTH_PROVIDER_URL=$AUTH_PROVIDER_URL
ENV AUTH_REALM=$AUTH_REALM
ENV AUTH_CLIENT_ID=$AUTH_CLIENT_ID
ENV AUTH_CLIENT_SECRET=$AUTH_CLIENT_SECRET

RUN npm run build

EXPOSE 3231

CMD [ "npm", "run", "server" ]
